export const auth: any = { currentUser: null };
export const db: any = null;
export const storage: any = null;
export const logOutUser = async () => {};
export const onAuthStateChanged = (auth: any, cb: any) => () => {};
export const handleRedirectResult = async () => null;
export const handleBunnyDBError = (err: any) => console.error(err);
export enum OperationType { READ, WRITE, DELETE }
export const collection = (...args: any[]) => null;
export const getDocs = async (...args: any[]) => ({ empty: true, docs: [] });
export const getDoc = async (...args: any[]) => ({ exists: false, data: () => null });
export const onSnapshot = (...args: any[]) => () => {};
export const query = (...args: any[]) => null;
export const orderBy = (...args: any[]) => null;
export const deleteDoc = async (...args: any[]) => {};
export const doc = (...args: any[]) => null;
export const where = (...args: any[]) => null;
export const setDoc = async (...args: any[]) => {};
export const updateDoc = async (...args: any[]) => {};
export const increment = (n: number) => n;
export const serverTimestamp = (...args: any[]) => Date.now();
export const signInWithPopup = async (...args: any[]) => null;
export const GoogleAuthProvider = class {};
export const signOut = async (...args: any[]) => {};
export const ref = (...args: any[]) => null;
export const uploadBytesResumable = (...args: any[]) => ({ on: () => {} });
export const getDownloadURL = async (...args: any[]) => "";
